env:
  global:
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64
  - secure: vv2UY5kTzDE4W3epNrcl7Vskt6Q12wmxpbJ8uLrVA1kjL+M9iXun8cqCOcAtStuC8jnC3RLByauQhxnhUxhWO10kK9DGMnmI0KU00Yy5RNe9iGrVmRA8xtT+RcfWpBe0RZMts30ablMjdPsvwvcDu6h1crU/bHg9tw4/YFm29D6UikFaZxvGLS2zXQsDBbzTQrOl1D1pCrPt5P33xLAapEnQa1EIJoA/pHWfmPcZCN//DUXth4mNVuUU96NxNO6KlBUaal/u+9QchDEt+0l+ruTT3DWVHEUFCnViRxKwUh2Wo+4p/wQ0n9Q+p7+NJjPjlWXPOgi7iNXeADmBeln4NlbO9byxkUPTKR85nGuB6c0ItpnpQQtXuKzxcMpbX86MvhKw94BgKihDcqo17Iu75Q1sxJ5I+NQlGbp9Tt0umLV/sbvWADVQYMZx3L+57dgOT16XETtCZ5sKAAyzHWQx59+orSKW68yx8gUDdlrACk8uULLK1UH8DGBNkY7qRq5aJpATlxnQMQw9/5y5yk+K2HTj+/nxFopdh4fCwppJsDpBzHFOvVSrX66i4TlL6iVyeK34k47dIYCUpXR9yVKP3rMCS6u/LkPW5bMT0nt68UWEacCD+cbCipej9bplKc3Xvh3NGuR5q3K+TczXBtksvjwtHZdBB33Fx/XmfJJArak=
  - secure: ivwrOd2DE0JTU8aY7pB7a5yMJcPZTd0fEChhBkbXBvSkAc7obouhBYOa0n50pE4srFjm1TfqrRY4tedkNjKtZSiFvZMbvyFH6NDSVs5ua1KWvRDVIJJvhjjYmGhyhQyUXL1Af9iq6i3chNHOQLCCrmg2WttsB/Js2E1ZUL/SCinN5xAU1W4c/X43to8xfYmHhyA0jCOoMKrNtvJBSi9x8Q2nIuY6VqbC5YPQS5uIaIDqYUwom/5GCctGJDJ3kxLQQujq0/UkKeir4M7St+A8yFfWziAKnIEiZgBz+lkAFXR+kCVJB8c3l20DUbOH4lnip6KD4vdYFhWwMA4uyLimy2o/z+G8bPR5zXfsA8x74nDb0S4hSlGN3pLdH3eOIcXiIk9LU4xbBZDJEztYzd1c1JFOwK1DhEBz5O6s8iOo/OfAqJgI6BfkhDg1acuUCAsSLv1jZKa5ElJYEwuBLj8p725Ood3f02U28nbWY1auGDTbGlN5Y6DeZ6/bL56wH3C7pwG8cJF9gotJCZAFc2raQ9xNo85Z+KQTRWwq9SjjNac5nYZD15qMLRDWhA8+lBdY+xI9rc4rIL/ccEsIJXNuFTnQm9p6XXWIBb6ZY5dHqxk39kkOGQJkF0Sdi0hC67F4h8CAUaL/ytyFc0SSwdiFV+ZtPYoVATpI+yGlgcNBlKM=

sudo: required

services:
- docker

script:
- docker build -t apache -f ./apache/Dockerfile ./apache

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=unibaktr/datkom-apache
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
- docker build -f ./apache/Dockerfile -t $REPO:$TAG ./apache
- docker push $REPO
