sudo: required

services:
- docker

script:
- docker build -t apache -f ./apache/Dockerfile ./apache

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=unibaktr/datkom-apache
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
- docker build -f ./apache/Dockerfile -t $REPO:$TAG ./apache
- docker push $REPO
- curl -X POST https://hooks.microbadger.com/images/unibaktr/datkom-apache/2JIe2c0gVocS5yczmWFUTxml03Q=
